### ISSUE TITLE
RangeError ios logEventWithParameters

### ISSUE THREAD

**Issue by devmobile-vulog** [flurry/flutter-flurry-sdk#8]
Hi,
I'm encountering an issue when using logEventWithParameters
```
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..6: 10768739056
#0      List.[] (dart:core-patch[/array.dart:273:36]())
#1      Flurry.logEventWithParameters
package:flutter_flurry_sdk/flurry.dart:272
<asynchronous suspension>
```

Working fine on android though

**Comment by poting-oath** [comment]
@hantao-flurrydev Either iOS's `flurryLogEventWithParameters` returns wrong number, or Flutter's `flurryAgent`/`eventRecordStatus` is undefined.

**Comment by devmobile-vulog** [comment]
From the debugger i don't see an issue with ```flurryAgent```/```eventRecordStatus```. 
But the int i'm getting back look like this : ```10801561344```
How could it be that ```flurryLogEventWithParameters``` returns wrong numbers ? Any ideas ?

**Comment by hantao-flurrydev** [comment]
Hi @devmobile-vulog , were you able to reproduce this issue?

**Comment by devmobile-vulog** [comment]
I'm not sure what you mean by duplicating. The issue is still there, and it looks like I have a correct instance of flurryAgent

**Comment by hantao-flurrydev** [comment]
I meant reproduce it during debug mode?

**Comment by devmobile-vulog** [comment]
Yes i am reproducing in debug

**Comment by hantao-flurrydev** [comment]
@devmobile-vulog would you mind sending us some sample code or snippet about how you did it, as we found an enum mismatched, but that will only affect the `logStandardEvent` api in flutter wrapper.

**Comment by devmobile-vulog** [comment]
I don't really have a sample code as i can't replicate it in another app. It is working fine when i start from scratch

**Comment by poting-oath** [comment]
Please try again on the latest flutter_flurry_sdk 2.2.0, to see whether it is still an issue. Thanks!

**Comment by poting-oath** [comment]
@devmobile-vulog Could you please try the latest release flutter_flurry_sdk 2.2.1? Thanks!

**Comment by devmobile-vulog** [comment]
I'm still getting the same issue `await Flurry.logEventWithParameters(eventName, {'test': 'test'});`
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): 10802054896
#0      List.[] (dart:core-patch/array.dart:282:36)
#1      Flurry.logEventWithParameters
package:flutter_flurry_sdk/flurry.dart:273
<asynchronous suspension>
#2      Analytic._flurryLogEvent
package:one_app/…/analytic/analytic.dart:177
<asynchronous suspension>

```

**Comment by devmobile-vulog** [comment]
Could we get any help on this ?

**Comment by poting-oath** [comment]
@hunterhays `FlurryFlutterPlugin.m` returns `NSNumber` back to `flurry_agent.dart`, but `flurry_agent.dart` expects to receive `int` instead. Is it possible the cause?

**Comment by flurrydev** [comment]
@devmobile-vulog We are actively investigating the issue. I have not yet been able to reproduce this error in my Flutter test app.
